### ISSUE TITLE
Strip down the code to core components

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/ExTreeMaker#5]

**Comment by OlivierBondu** [comment]
Can we delete the present stuff we compile in [interface](https://github.com/cp3-llbb/ExTreeMaker/tree/dev_goingMiniAOD/interface), [plugins](https://github.com/cp3-llbb/ExTreeMaker/tree/dev_goingMiniAOD/plugins) and [src](https://github.com/cp3-llbb/ExTreeMaker/tree/dev_goingMiniAOD/src) ?

@BrieucF , @acaudron , @AlexandreMertens @delaere ?

**Comment by delaere** [comment]
ok for me.

**Comment by acaudron** [comment]
You may want to keep the code to compute the b-tagging reweighting but you may also clean it a bit or change it so I let you see how you want to proceed for that.
The other things can be removed without problem as they were mainly there for producing the PAT samples.

**Comment by delaere** [comment]
For the b-tag reweighting, we will have to discuss about the best option for run2. The promote/demote approach may be more flexible.

**Comment by OlivierBondu** [comment]
cleaned up in https://github.com/cp3-llbb/ExTreeMaker/pull/17
